// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQzUmclEiUWQ3OCxIZY-Y5gKG8JtS3gE4',
    appId: '1:670564351875:web:e291e9a032a462ae25c0b6',
    messagingSenderId: '670564351875',
    projectId: 'registro-colegio-ale',
    authDomain: 'registro-colegio-ale.firebaseapp.com',
    storageBucket: 'registro-colegio-ale.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5NsiOPJMZI8syiPkF4XZN9GHrU3z8LBU',
    appId: '1:670564351875:android:6ce1248821820bad25c0b6',
    messagingSenderId: '670564351875',
    projectId: 'registro-colegio-ale',
    storageBucket: 'registro-colegio-ale.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjpfmpNux2e9k0RIR_20xgeEW0lFw8tqo',
    appId: '1:670564351875:ios:870dc96bcd0963d725c0b6',
    messagingSenderId: '670564351875',
    projectId: 'registro-colegio-ale',
    storageBucket: 'registro-colegio-ale.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjpfmpNux2e9k0RIR_20xgeEW0lFw8tqo',
    appId: '1:670564351875:ios:870dc96bcd0963d725c0b6',
    messagingSenderId: '670564351875',
    projectId: 'registro-colegio-ale',
    storageBucket: 'registro-colegio-ale.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQzUmclEiUWQ3OCxIZY-Y5gKG8JtS3gE4',
    appId: '1:670564351875:web:5cc895e05c4745fd25c0b6',
    messagingSenderId: '670564351875',
    projectId: 'registro-colegio-ale',
    authDomain: 'registro-colegio-ale.firebaseapp.com',
    storageBucket: 'registro-colegio-ale.firebasestorage.app',
  );
}
